import "@supabase/functions-js/edge-runtime.d.ts";
import nodemailer from "npm:nodemailer@6.9.11";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

Deno.serve(async (req) => {
  // Handle CORS preflight request
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const { to_email, client_name, invoice_number, pdf_base64 } = await req.json();

    if (!to_email || !pdf_base64) {
      throw new Error("Missing required fields (to_email, pdf_base64)");
    }

    // SMTP Configuration for LTS (cPanel)
    const transporter = nodemailer.createTransport({
       host: "mail.ispcfacil.co.mz",
       port: 465,
       secure: true, // true for 465, false for other ports
       auth: {
         user: "notifications@ispcfacil.co.mz",
         pass: "&fF1;s*QJ$dJ",
       },
    });

    // Clean up base64 prefix if generated by standard tools
    const base64Data = pdf_base64.replace(/^data:application\/pdf;base64,/, "");

    // Email Data
    const mailOptions = {
      from: '"ISPC Fácil" <notifications@ispcfacil.co.mz>',
      to: to_email,
      subject: `Factura ${invoice_number} - ISPC Fácil`,
      text: `Olá ${client_name},\n\nEm anexo, enviamos a sua factura ${invoice_number}.\n\nObrigado,\nEquipa ISPC Fácil`,
      html: `
        <div style="font-family: sans-serif; padding: 20px; max-width: 600px; margin: 0 auto; border: 1px solid #eee; border-radius: 8px;">
          <h2 style="color: #f97316;">ISPC Fácil</h2>
          <p>Olá <strong>${client_name || 'Cliente'}</strong>,</p>
          <p>Confirmamos a emissão da sua factura <strong>${invoice_number}</strong>. O documento encontra-se em anexo a este e-mail em formato PDF.</p>
          <br/>
          <p>Cumprimentos,<br/>Equipe LTS - ISPC Fácil</p>
          <hr style="border: none; border-top: 1px solid #eee; margin-top: 30px;"/>
          <p style="font-size: 11px; color: #888;">Este é um e-mail automático. Por favor, não responda directamente para este endereço.</p>
        </div>
      `,
      attachments: [
        {
          filename: `Factura_${(invoice_number || 'ND').replace(/\//g, '-')}.pdf`,
          content: base64Data,
          encoding: 'base64'
        }
      ]
    };

    // Send the email
    const info = await transporter.sendMail(mailOptions);
    console.log("Message sent: %s", info.messageId);

    return new Response(
      JSON.stringify({ success: true, messageId: info.messageId }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("Failed to send email:", error);
    return new Response(
      JSON.stringify({ success: false, error: (error as Error).message }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" }, status: 500 }
    );
  }
});
